ui: mocha-bdd
browsers:
  - name: chrome
    version: -2..latest
  - name: ie
    version: [10, 11]
  - name: edge
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: -2..latest
